CREATE TABLE authorisation (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE products (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    price BIGINT NOT NULL CHECK (price > 0),
    text VARCHAR(200) NOT NULL,
    image VARCHAR(200) NOT NULL,
    stars FLOAT NOT NULL CHECK (stars > 0),
    is_new BOOLEAN NOT NULL,
    is_bestseller BOOLEAN NOT NULL
);